### ISSUE TITLE
Question about generated routing table

### ISSUE THREAD

**Issue by ileneruth** [fortinet/ibm-fortigate-terraform-deploy#17]
I notice that a routing table is created in vpc.tf, but it's not bound to any subnets and doesn't have any rules.  What is the intended purpose of this routing table?

**Comment by Joel-Cripps** [comment]
Hey Ilene, I believe this is just a vestige from the original, we no longer have that section in the HA version.
@fshuva  can you remove that in the next release?

**Comment by ileneruth** [comment]
Thanks @Joel-Cripps .  I think this terraform still backs the single instance IBM catalog offering - I assume it's still ok to use, even though the HA is there as well?

**Comment by Joel-Cripps** [comment]
Yes of course. HA is a separate repo. If you are looking for a CLI/local based terraform deploy you can check out our other repos here: https://github.com/fortinet/fortigate-terraform-deploy/tree/main/ibm

**Comment by ileneruth** [comment]
Ah ok, thanks for the link - I may switch over.   I'm incorporating the terraform into a larger 'landing zone'.  I've forked this repository (https://github.com/ibmcloud-tech-canada/ibm-fortigate-terraform-deploy) and made some updates, like ensuring all resources land in a resource group, and I have another update coming that takes a customer provided key to encrypt the boot and data volumes.  I also had to remove the provider block to use as a module in a larger script.

**Comment by Joel-Cripps** [comment]
Sounds good. PR's are welcome if you want to send some of the changes this way. Otherwise when you have finished send us the link and maybe we can incorporate some of the changes.  Customer provided keys to encrypt would be a useful addition for sure.
