### ISSUE TITLE
Its not possible to declare Resource Group where firewalls will be deployed.

### ISSUE THREAD

**Issue by rsbmagalhaes** [fortinet/ibm-fortigate-terraform-deploy#21]
Hello!

It was great to have your deploy automation in IBM Cloud.

I tried to use it in a customer but he had a requirement to specify a Resource Group. I solved that customizing your terraform to allow the customer deploy with a Resource Group variable.

I would suggest you to update the code inserting a Resource group variable.

If you want, I'm able to help with anything.

Thanks a lot

**Comment by Joel-Cripps** [comment]
PR's are welcome. Feel free to submit one with the changes.

**Comment by rsbmagalhaes** [comment]
Guys, I inserted the Resource Group field in var in the instance files. I sent a pull request. Thanks.
